create table if not exists public.service_inventory_service_types (
  id bigint generated by default as identity primary key,
  name text unique not null,
  is_base boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.service_inventory_service_types
add column if not exists is_base boolean not null default false;

alter table public.service_inventory_service_types
add column if not exists is_active boolean not null default true;

alter table public.service_inventory_service_types
add column if not exists created_at timestamptz not null default now();

create unique index if not exists service_inventory_service_types_name_lower_idx
on public.service_inventory_service_types (lower(name));

create table if not exists public.service_inventory_material_types (
  id bigint generated by default as identity primary key,
  name text unique not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.service_inventory_material_types
add column if not exists is_active boolean not null default true;

alter table public.service_inventory_material_types
add column if not exists created_at timestamptz not null default now();

create unique index if not exists service_inventory_material_types_name_lower_idx
on public.service_inventory_material_types (lower(name));

create table if not exists public.service_inventory_service_type_materials (
  id bigint generated by default as identity primary key,
  service_type_id bigint not null references public.service_inventory_service_types(id) on delete cascade,
  material_type_id bigint not null references public.service_inventory_material_types(id) on delete cascade,
  unique(service_type_id, material_type_id)
);

alter table public.service_inventory_service_types enable row level security;
alter table public.service_inventory_material_types enable row level security;
alter table public.service_inventory_service_type_materials enable row level security;

drop policy if exists "Allow full access service inventory service types" on public.service_inventory_service_types;
create policy "Allow full access service inventory service types"
on public.service_inventory_service_types
for all
using (true)
with check (true);

drop policy if exists "Allow full access service inventory material types" on public.service_inventory_material_types;
create policy "Allow full access service inventory material types"
on public.service_inventory_material_types
for all
using (true)
with check (true);

drop policy if exists "Allow full access service inventory service type materials" on public.service_inventory_service_type_materials;
create policy "Allow full access service inventory service type materials"
on public.service_inventory_service_type_materials
for all
using (true)
with check (true);

insert into public.service_inventory_service_types (name, is_base, is_active)
values
  ('Service / Λάδια', true, true),
  ('Φρένα', true, true),
  ('Ελαστικά', true, true),
  ('Μπαταρία', true, true),
  ('Άλλο', true, true)
on conflict (name) do update
set is_base = true,
    is_active = true;

insert into public.service_inventory_material_types (name, is_active)
values
  ('Λάδι', true),
  ('Φίλτρο λαδιού', true),
  ('Φίλτρο αέρα', true),
  ('Φίλτρο καμπίνας', true),
  ('Τακάκια', true),
  ('Δισκόπλακες', true),
  ('Υγρά φρένων', true),
  ('Ελαστικά', true),
  ('Μπαταρία', true),
  ('Άλλο', true)
on conflict (name) do update
set is_active = true;

insert into public.service_inventory_service_type_materials (service_type_id, material_type_id)
select service_type.id, material_type.id
from public.service_inventory_service_types service_type
join public.service_inventory_material_types material_type
  on (
    (service_type.name = 'Service / Λάδια' and material_type.name in ('Λάδι', 'Φίλτρο λαδιού', 'Φίλτρο αέρα', 'Φίλτρο καμπίνας'))
    or (service_type.name = 'Φρένα' and material_type.name in ('Τακάκια', 'Δισκόπλακες', 'Υγρά φρένων'))
    or (service_type.name = 'Ελαστικά' and material_type.name = 'Ελαστικά')
    or (service_type.name = 'Μπαταρία' and material_type.name = 'Μπαταρία')
    or (service_type.name = 'Άλλο' and material_type.name = 'Άλλο')
  )
on conflict (service_type_id, material_type_id) do nothing;
