CREATE TABLE IF NOT EXISTS leasing_contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  tax_id TEXT,
  phone TEXT,
  vehicle_description TEXT NOT NULL,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  down_payment NUMERIC NOT NULL DEFAULT 0,
  down_payment_transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
  remaining_amount NUMERIC NOT NULL DEFAULT 0,
  installments_count INTEGER NOT NULL DEFAULT 0,
  monthly_payment NUMERIC NOT NULL DEFAULT 0,
  start_date DATE,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS leasing_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  leasing_contract_id BIGINT NOT NULL REFERENCES leasing_contracts(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL DEFAULT 0,
  payment_date DATE NOT NULL,
  payment_method TEXT NOT NULL,
  notes TEXT,
  transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_leasing_contracts_status
ON leasing_contracts(status);

ALTER TABLE leasing_contracts
ADD COLUMN IF NOT EXISTS car_id BIGINT;

ALTER TABLE leasing_contracts
ADD COLUMN IF NOT EXISTS down_payment_transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL;

ALTER TABLE leasing_contracts
ADD COLUMN IF NOT EXISTS installments_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE leasing_contracts
DROP CONSTRAINT IF EXISTS leasing_contracts_down_payment_transaction_id_fkey;

ALTER TABLE leasing_contracts
ADD CONSTRAINT leasing_contracts_down_payment_transaction_id_fkey
FOREIGN KEY (down_payment_transaction_id)
REFERENCES transactions(id)
ON DELETE SET NULL;

ALTER TABLE leasing_contracts
DROP CONSTRAINT IF EXISTS leasing_contracts_car_id_fkey;

ALTER TABLE leasing_contracts
ADD CONSTRAINT leasing_contracts_car_id_fkey
FOREIGN KEY (car_id)
REFERENCES cars(id)
ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_leasing_contracts_car_id
ON leasing_contracts(car_id);

CREATE INDEX IF NOT EXISTS idx_leasing_payments_contract_id
ON leasing_payments(leasing_contract_id);

ALTER TABLE leasing_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE leasing_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read leasing contracts" ON leasing_contracts;
CREATE POLICY "Allow read leasing contracts"
ON leasing_contracts
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow insert leasing contracts" ON leasing_contracts;
CREATE POLICY "Allow insert leasing contracts"
ON leasing_contracts
FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update leasing contracts" ON leasing_contracts;
CREATE POLICY "Allow update leasing contracts"
ON leasing_contracts
FOR UPDATE
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read leasing payments" ON leasing_payments;
CREATE POLICY "Allow read leasing payments"
ON leasing_payments
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow insert leasing payments" ON leasing_payments;
CREATE POLICY "Allow insert leasing payments"
ON leasing_payments
FOR INSERT
WITH CHECK (true);
