create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.expense_categories enable row level security;

drop policy if exists "Allow read expense categories" on public.expense_categories;
create policy "Allow read expense categories"
on public.expense_categories
for select
using (true);

drop policy if exists "Allow insert expense categories" on public.expense_categories;
create policy "Allow insert expense categories"
on public.expense_categories
for insert
with check (true);

insert into public.expense_categories (name)
values
  ('Service'),
  ('Ασφάλεια'),
  ('ΚΤΕΟ'),
  ('Τέλη Κυκλοφορίας'),
  ('Ελαστικά'),
  ('Ανταλλακτικά'),
  ('Φανοποιείο'),
  ('Καύσιμα'),
  ('Πλύσιμο'),
  ('Λοιπά')
on conflict (name) do nothing;

alter table public.transactions
add column if not exists supplier_id bigint;

alter table public.transactions
drop constraint if exists transactions_supplier_id_fkey;

alter table public.transactions
add constraint transactions_supplier_id_fkey
foreign key (supplier_id)
references public.suppliers (id)
on delete set null;

create index if not exists idx_transactions_supplier_id
on public.transactions (supplier_id);

create or replace view public.supplier_ledger_view as
select
  s.id as supplier_id,
  s.name as supplier_name,
  coalesce(sum(
    case
      when t.type = 'expense' and t.payment_method = 'credit'
      then t.amount
      else 0
    end
  ), 0) as total_credit_charges,
  coalesce(sum(
    case
      when t.type = 'supplier_payment'
      then t.amount
      else 0
    end
  ), 0) as total_payments,
  coalesce(sum(
    case
      when t.type = 'expense' and t.payment_method = 'credit'
      then t.amount
      when t.type = 'supplier_payment'
      then -t.amount
      else 0
    end
  ), 0) as outstanding_balance
from public.suppliers s
left join public.transactions t
  on t.supplier_id = s.id
group by s.id, s.name
order by s.name;
