create table if not exists public.service_inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('oil', 'oil_filter', 'cabin_filter', 'air_filter', 'brakes', 'belts', 'tire', 'battery', 'other')),
  brand text,
  size_or_spec text,
  supplier_id bigint references public.suppliers(id) on delete set null,
  unit_cost numeric(12,2) not null default 0,
  current_stock numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.service_inventory_movements (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.service_inventory_items(id) on delete cascade,
  car_id bigint null references public.cars(id) on delete set null,
  service_id bigint null references public.services(id) on delete set null,
  movement_type text not null check (movement_type in ('purchase', 'usage', 'adjustment')),
  quantity numeric(12,2) not null,
  unit_cost numeric(12,2) not null default 0,
  total_cost numeric(12,2) not null default 0,
  supplier_id bigint references public.suppliers(id) on delete set null,
  payment_method text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists service_inventory_items_type_idx
on public.service_inventory_items (type);

create index if not exists service_inventory_movements_item_id_idx
on public.service_inventory_movements (item_id);

create index if not exists service_inventory_movements_created_at_idx
on public.service_inventory_movements (created_at desc);

alter table public.service_inventory_items enable row level security;
alter table public.service_inventory_movements enable row level security;

drop policy if exists "Allow full access service inventory items" on public.service_inventory_items;
create policy "Allow full access service inventory items"
on public.service_inventory_items
for all
using (true)
with check (true);

drop policy if exists "Allow full access service inventory movements" on public.service_inventory_movements;
create policy "Allow full access service inventory movements"
on public.service_inventory_movements
for all
using (true)
with check (true);
