CREATE TABLE IF NOT EXISTS financial_obligations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  down_payment NUMERIC(12, 2) NOT NULL DEFAULT 0,
  seasons_count INTEGER NOT NULL DEFAULT 1,
  months_per_season INTEGER NOT NULL DEFAULT 1,
  start_month INTEGER NOT NULL DEFAULT 1,
  start_year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INTEGER,
  payment_method TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
);

ALTER TABLE financial_obligations
ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS down_payment NUMERIC(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS seasons_count INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS months_per_season INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS start_month INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS start_year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM NOW())::INTEGER,
ADD COLUMN IF NOT EXISTS payment_method TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE financial_obligations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read financial obligations" ON financial_obligations;
CREATE POLICY "Allow read financial obligations"
ON financial_obligations
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow insert financial obligations" ON financial_obligations;
CREATE POLICY "Allow insert financial obligations"
ON financial_obligations
FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update financial obligations" ON financial_obligations;
CREATE POLICY "Allow update financial obligations"
ON financial_obligations
FOR UPDATE
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete financial obligations" ON financial_obligations;
CREATE POLICY "Allow delete financial obligations"
ON financial_obligations
FOR DELETE
USING (true);
