CREATE TABLE IF NOT EXISTS car_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  notes TEXT
);

ALTER TABLE car_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read car documents" ON car_documents;
CREATE POLICY "Allow read car documents"
ON car_documents
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow insert car documents" ON car_documents;
CREATE POLICY "Allow insert car documents"
ON car_documents
FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete car documents" ON car_documents;
CREATE POLICY "Allow delete car documents"
ON car_documents
FOR DELETE
USING (true);

INSERT INTO storage.buckets (id, name, public)
VALUES ('car-documents', 'car-documents', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

DROP POLICY IF EXISTS "Allow read car document files" ON storage.objects;
CREATE POLICY "Allow read car document files"
ON storage.objects
FOR SELECT
USING (bucket_id = 'car-documents');

DROP POLICY IF EXISTS "Allow upload car document files" ON storage.objects;
CREATE POLICY "Allow upload car document files"
ON storage.objects
FOR INSERT
WITH CHECK (bucket_id = 'car-documents');

DROP POLICY IF EXISTS "Allow delete car document files" ON storage.objects;
CREATE POLICY "Allow delete car document files"
ON storage.objects
FOR DELETE
USING (bucket_id = 'car-documents');
